Attaching to mongo, rp2, webserver
[33mrp2          |[0m 
[33mrp2          |[0m > rp2@0.0.1 init:std /
[33mrp2          |[0m > node ./bin/www
[33mrp2          |[0m 
[36mmongo        |[0m 2019-11-29T18:19:47.299+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=7a90b3e600e6
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] db version v4.2.1
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] git version: edf6d45851c0b9ee15548f0f847df141764a317e
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] modules: none
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] build environment:
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten]     distarch: x86_64
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
[36mmongo        |[0m 2019-11-29T18:19:47.302+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
[36mmongo        |[0m 2019-11-29T18:19:47.313+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[36mmongo        |[0m 2019-11-29T18:19:47.318+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
[33mrp2          |[0m /app.js:21
[33mrp2          |[0m   uri,
[33mrp2          |[0m   ^
[33mrp2          |[0m 
[33mrp2          |[0m ReferenceError: uri is not defined
[33mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[33mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[33mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[33mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[33mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[33mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[33mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[33mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[33mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[33mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[33mrp2          |[0m npm ERR! code ELIFECYCLE
[33mrp2          |[0m npm ERR! errno 1
[33mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[33mrp2          |[0m npm ERR! Exit status 1
[33mrp2          |[0m npm ERR! 
[33mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[33mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[33mrp2          |[0m 
[33mrp2          |[0m npm ERR! A complete log of this run can be found in:
[33mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_19_50_491Z-debug.log
[35mrp2          |[0m 
[35mrp2          |[0m > rp2@0.0.1 init:std /
[35mrp2          |[0m > node ./bin/www
[35mrp2          |[0m 
[35mrp2          |[0m /app.js:21
[35mrp2          |[0m   uri,
[35mrp2          |[0m   ^
[35mrp2          |[0m 
[35mrp2          |[0m ReferenceError: uri is not defined
[35mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[35mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[35mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[35mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[35mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[35mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[35mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[35mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[35mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[35mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[35mrp2          |[0m npm ERR! code ELIFECYCLE
[35mrp2          |[0m npm ERR! errno 1
[35mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[35mrp2          |[0m npm ERR! Exit status 1
[35mrp2          |[0m npm ERR! 
[35mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[35mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[35mrp2          |[0m 
[35mrp2          |[0m npm ERR! A complete log of this run can be found in:
[35mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_19_55_891Z-debug.log
[33mrp2 exited with code 1
[0m[36mmongo        |[0m 2019-11-29T18:19:57.685+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051597:685610][1:0x7fab79cc6b00], txn-recover: Recovering log 62 through 63
[36mmongo        |[0m 2019-11-29T18:19:58.040+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051598:40472][1:0x7fab79cc6b00], txn-recover: Recovering log 63 through 63
[36mmongo        |[0m 2019-11-29T18:19:58.411+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051598:411269][1:0x7fab79cc6b00], txn-recover: Main recovery loop: starting at 62/10496 to 63/256
[36mmongo        |[0m 2019-11-29T18:19:58.917+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051598:917307][1:0x7fab79cc6b00], txn-recover: Recovering log 62 through 63
[36mmongo        |[0m 2019-11-29T18:19:59.366+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051599:366079][1:0x7fab79cc6b00], txn-recover: Recovering log 63 through 63
[36mmongo        |[0m 2019-11-29T18:19:59.409+0000 I  STORAGE  [initandlisten] WiredTiger message [1575051599:409741][1:0x7fab79cc6b00], txn-recover: Set global recovery timestamp: (0,0)
[36mmongo        |[0m 2019-11-29T18:19:59.429+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
[36mmongo        |[0m 2019-11-29T18:19:59.442+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
[36mmongo        |[0m 2019-11-29T18:19:59.445+0000 I  CONTROL  [initandlisten] 
[36mmongo        |[0m 2019-11-29T18:19:59.446+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[36mmongo        |[0m 2019-11-29T18:19:59.446+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[36mmongo        |[0m 2019-11-29T18:19:59.447+0000 I  CONTROL  [initandlisten] 
[36mmongo        |[0m 2019-11-29T18:19:59.458+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
[36mmongo        |[0m 2019-11-29T18:19:59.464+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
[36mmongo        |[0m 2019-11-29T18:19:59.465+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
[36mmongo        |[0m 2019-11-29T18:19:59.466+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
Creating network "docker_default" with the default driver
Creating mongo ... 
[1A[2KCreating mongo ... [32mdone[0m[1BCreating rp2   ... 
[1A[2KCreating rp2   ... [32mdone[0m[1BCreating webserver ... 
[1A[2KCreating webserver ... [32mdone[0m[1B[36mmongo        |[0m 2019-11-29T18:19:59.473+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
[36mmongo        |[0m 2019-11-29T18:19:59.475+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[36mmongo        |[0m 2019-11-29T18:19:59.478+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
[36mmongo        |[0m 2019-11-29T18:19:59.479+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
[36mmongo        |[0m 2019-11-29T18:19:59.479+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
[36mmongo        |[0m 2019-11-29T18:19:59.479+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
[36mmongo        |[0m 2019-11-29T18:19:59.480+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
[31mrp2          |[0m 
[31mrp2          |[0m > rp2@0.0.1 init:std /
[31mrp2          |[0m > node ./bin/www
[31mrp2          |[0m 
[36mmongo        |[0m 2019-11-29T18:20:00.071+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
[31mrp2          |[0m /app.js:21
[31mrp2          |[0m   uri,
[31mrp2          |[0m   ^
[31mrp2          |[0m 
[31mrp2          |[0m ReferenceError: uri is not defined
[31mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[31mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[31mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[31mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[31mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[31mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[31mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[31mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[31mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[31mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[31mrp2          |[0m npm ERR! code ELIFECYCLE
[31mrp2          |[0m npm ERR! errno 1
[31mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[31mrp2          |[0m npm ERR! Exit status 1
[31mrp2          |[0m npm ERR! 
[31mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[31mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[31mrp2          |[0m 
[31mrp2          |[0m npm ERR! A complete log of this run can be found in:
[31mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_01_249Z-debug.log
[35mrp2 exited with code 1
[0m[34mrp2          |[0m 
[34mrp2          |[0m > rp2@0.0.1 init:std /
[34mrp2          |[0m > node ./bin/www
[34mrp2          |[0m 
[34mrp2          |[0m /app.js:21
[34mrp2          |[0m   uri,
[34mrp2          |[0m   ^
[34mrp2          |[0m 
[34mrp2          |[0m ReferenceError: uri is not defined
[34mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[34mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[34mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[34mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[34mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[34mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[34mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[34mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[34mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[34mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[34mrp2          |[0m npm ERR! code ELIFECYCLE
[34mrp2          |[0m npm ERR! errno 1
[34mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[34mrp2          |[0m npm ERR! Exit status 1
[34mrp2          |[0m npm ERR! 
[34mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[34mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[34mrp2          |[0m 
[34mrp2          |[0m npm ERR! A complete log of this run can be found in:
[34mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_06_613Z-debug.log
[31mrp2 exited with code 1
[0m[36;1mrp2          |[0m 
[36;1mrp2          |[0m > rp2@0.0.1 init:std /
[36;1mrp2          |[0m > node ./bin/www
[36;1mrp2          |[0m 
[36;1mrp2          |[0m /app.js:21
[36;1mrp2          |[0m   uri,
[36;1mrp2          |[0m   ^
[36;1mrp2          |[0m 
[36;1mrp2          |[0m ReferenceError: uri is not defined
[36;1mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[36;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[36;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[36;1mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[36;1mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[36;1mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[36;1mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[36;1mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[36;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[36;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[36;1mrp2          |[0m npm ERR! code ELIFECYCLE
[36;1mrp2          |[0m npm ERR! errno 1
[36;1mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[36;1mrp2          |[0m npm ERR! Exit status 1
[36;1mrp2          |[0m npm ERR! 
[36;1mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[36;1mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[36;1mrp2          |[0m 
[36;1mrp2          |[0m npm ERR! A complete log of this run can be found in:
[36;1mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_11_687Z-debug.log
[34mrp2 exited with code 1
[0m[33;1mrp2          |[0m 
[33;1mrp2          |[0m > rp2@0.0.1 init:std /
[33;1mrp2          |[0m > node ./bin/www
[33;1mrp2          |[0m 
[33;1mrp2          |[0m /app.js:21
[33;1mrp2          |[0m   uri,
[33;1mrp2          |[0m   ^
[33;1mrp2          |[0m 
[33;1mrp2          |[0m ReferenceError: uri is not defined
[33;1mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[33;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[33;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[33;1mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[33;1mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[33;1mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[33;1mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[33;1mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[33;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[33;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[33;1mrp2          |[0m npm ERR! code ELIFECYCLE
[33;1mrp2          |[0m npm ERR! errno 1
[33;1mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[33;1mrp2          |[0m npm ERR! Exit status 1
[33;1mrp2          |[0m npm ERR! 
[33;1mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[33;1mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[33;1mrp2          |[0m 
[33;1mrp2          |[0m npm ERR! A complete log of this run can be found in:
[33;1mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_16_919Z-debug.log
[36;1mrp2 exited with code 1
[0m[32;1mrp2          |[0m 
[32;1mrp2          |[0m > rp2@0.0.1 init:std /
[32;1mrp2          |[0m > node ./bin/www
[32;1mrp2          |[0m 
[32;1mrp2          |[0m /app.js:21
[32;1mrp2          |[0m   uri,
[32;1mrp2          |[0m   ^
[32;1mrp2          |[0m 
[32;1mrp2          |[0m ReferenceError: uri is not defined
[32;1mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[32;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[32;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[32;1mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[32;1mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[32;1mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[32;1mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[32;1mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[32;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[32;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[32;1mrp2          |[0m npm ERR! code ELIFECYCLE
[32;1mrp2          |[0m npm ERR! errno 1
[32;1mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[32;1mrp2          |[0m npm ERR! Exit status 1
[32;1mrp2          |[0m npm ERR! 
[32;1mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[32;1mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[32;1mrp2          |[0m 
[32;1mrp2          |[0m npm ERR! A complete log of this run can be found in:
[32;1mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_22_795Z-debug.log
[33;1mrp2 exited with code 1
[0m[35;1mrp2          |[0m 
[35;1mrp2          |[0m > rp2@0.0.1 init:std /
[35;1mrp2          |[0m > node ./bin/www
[35;1mrp2          |[0m 
[35;1mrp2          |[0m /app.js:21
[35;1mrp2          |[0m   uri,
[35;1mrp2          |[0m   ^
[35;1mrp2          |[0m 
[35;1mrp2          |[0m ReferenceError: uri is not defined
[35;1mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[35;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[35;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[35;1mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[35;1mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[35;1mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[35;1mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[35;1mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[35;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[35;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[35;1mrp2          |[0m npm ERR! code ELIFECYCLE
[35;1mrp2          |[0m npm ERR! errno 1
[35;1mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[35;1mrp2          |[0m npm ERR! Exit status 1
[35;1mrp2          |[0m npm ERR! 
[35;1mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[35;1mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[35;1mrp2          |[0m 
[35;1mrp2          |[0m npm ERR! A complete log of this run can be found in:
[35;1mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_31_854Z-debug.log
[32;1mrp2 exited with code 1
[0m[31;1mrp2          |[0m 
[31;1mrp2          |[0m > rp2@0.0.1 init:std /
[31;1mrp2          |[0m > node ./bin/www
[31;1mrp2          |[0m 
[31;1mrp2          |[0m /app.js:21
[31;1mrp2          |[0m   uri,
[31;1mrp2          |[0m   ^
[31;1mrp2          |[0m 
[31;1mrp2          |[0m ReferenceError: uri is not defined
[31;1mrp2          |[0m     at Object.<anonymous> (/app.js:21:3)
[31;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[31;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[31;1mrp2          |[0m     at Module.load (internal/modules/cjs/loader.js:914:32)
[31;1mrp2          |[0m     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[31;1mrp2          |[0m     at Module.require (internal/modules/cjs/loader.js:956:19)
[31;1mrp2          |[0m     at require (internal/modules/cjs/helpers.js:74:18)
[31;1mrp2          |[0m     at Object.<anonymous> (/bin/www:7:11)
[31;1mrp2          |[0m     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[31;1mrp2          |[0m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[31;1mrp2          |[0m npm ERR! code ELIFECYCLE
[31;1mrp2          |[0m npm ERR! errno 1
[31;1mrp2          |[0m npm ERR! rp2@0.0.1 init:std: `node ./bin/www`
[31;1mrp2          |[0m npm ERR! Exit status 1
[31;1mrp2          |[0m npm ERR! 
[31;1mrp2          |[0m npm ERR! Failed at the rp2@0.0.1 init:std script.
[31;1mrp2          |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[31;1mrp2          |[0m 
[31;1mrp2          |[0m npm ERR! A complete log of this run can be found in:
[31;1mrp2          |[0m npm ERR!     /root/.npm/_logs/2019-11-29T18_20_47_167Z-debug.log
[35;1mrp2 exited with code 1
[0m